name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry 
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Bum version 
        run: |
          poetry version patch
          poetry version
      - name: Commit and push changes
        run:
          git config --global user.name "Ewald Verhoeven" && 
          git config --global user.email "my@email.com" &&
          git status
          # git add -A 
          # git commit -m "bump version"
          # git push 
      # - name: Install dependencies
      #   run: poetry install
      # - name: Run flake8
      #   run: |
      #     poetry run flake8
      # - name: Test
      #   run: poetry run pytest

