name: Publish package (Pypi)

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: Release type
        options: 
        - major
        - minor
        - patch
        - premajor
        - preminor
        - prepatch
        - prerelease

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry 
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Get new version
        run: |
          echo "new_version=$(poetry version ${{github.event.inputs.type}} --dry-run -s)" >> $GITHUB_ENV
      - name: output version
        run: echo ${env.new_version}

      # - name: Commit and push changes
      #   run:
      #     git config --global user.name "Ewald91" && 
      #     git config --global user.email "ewaldverhoeven@hotmail.com" &&
      #     git status &&
      #     git add -A &&
      #     git commit -m "bump version" &&
      #     git push 
      # - name: Set poetry configurations
      #   run: |
      #     poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }} &&
      #     poetry config http-basic.pypi ${{ secrets.PYPI_USERNAME }} ${{ secrets.PYPI.PASSWORD }}
      # - name: Publish package to pypi-token.pypi
      #   run: |
      #     poetry publish

