name: Publish package (Pypi)

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry 
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Set version variable
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV &&
          echo "$GITHUB_ENV"

      # - name: Bump version 
      #   run: |
      #     poetry version patch
      #     poetry version
      # - name: Commit and push changes
      #   run:
      #     git config --global user.name "Ewald91" && 
      #     git config --global user.email "ewaldverhoeven@hotmail.com" &&
      #     git status &&
      #     git add -A &&
      #     git commit -m "bump version" &&
      #     git push 
      # - name: Set poetry configurations
      #   run: |
      #     poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }} &&
      #     poetry config http-basic.pypi ${{ secrets.PYPI_USERNAME }} ${{ secrets.PYPI.PASSWORD }}
      # - name: Publish package to pypi-token.pypi
      #   run: |
      #     poetry publish

